### ISSUE TITLE
STT class init with wrong config

### ISSUE THREAD

**Issue by emphasize** [OpenVoiceOS/ovos-plugin-manager#132]
config passed: 
```python
{
        "module": "ovos-stt-plugin-server",
        "ovos-stt-plugin-server": {
            "url": "https://stt.openvoiceos.com/stt",
            "lang": "de-de"
}
```

`get_stt_config` will now mangle the config and returns (as config)
```python
{
            "url": "https://stt.openvoiceos.com/stt",
            "lang": "de-de",
            "module": "ovos-stt-plugin-server"
}
```

since it has its own definitions.

_but_ `plugin_config = config.get(plugin) or {}` will produce an empty dict and the class will get initialized with this empty dict

https://github.com/OpenVoiceOS/ovos-plugin-manager/blob/c5a1d7dfde85036615918f8864a524936b2eda94/ovos_plugin_manager/stt.py#L130-L135

---------------

Because it (the module) has its own definition it's irrelevant if you pass
```python
{ "stt":
      {
        "module": "ovos-stt-plugin-server",
        "ovos-stt-plugin-server": {
            "url": "https://stt.openvoiceos.com/stt",
            "lang": "de-de"
      }
}
```

The result will be the same.

-----------------

Reproduce with:
```python
from ovos_plugin_manager.stt import OVOSSTTFactory
config={"module": "ovos-stt-plugin-server",
        "ovos-stt-plugin-server": {
        "url": "https://stt.openvoiceos.com/stt",
        "lang": "de-de"}}
engine = OVOSSTTFactory.create(config)
print(engine.url)
# https://stt.strongthany.cc/stt
```

**Comment by emphasize** [comment]
My suggestion:

```python
@staticmethod
    def get_class(config=None):

        # config = config or get_stt_config()
        config = get_stt_config(config)                                                
        stt_module = config["module"]
        if stt_module in OVOSSTTFactory.MAPPINGS:
            stt_module = OVOSSTTFactory.MAPPINGS[stt_module]
        return load_stt_plugin(stt_module)

    @staticmethod
    def create(config=None):
        
        # config = get_stt_config(config)
        # plugin = config["module"]
        # plugin_config = config.get(plugin) or {}
        try:
            clazz = OVOSSTTFactory.get_class(config)
            return clazz(config)
        except Exception:
            LOG.exception('The selected STT plugin could not be loaded!')
            raise
```

works with whole config or section. But you have the bigger picture.

**Comment by emphasize** [comment]
Imagine my head exploding when realizing this is not reproducable on another machine.

But - in my estimation - the "fix" made along the way covers the initial problem: that the class is initiated with an emtpy dict,
although it is configured with the intended structure.
```
{
    "module": "xxx",
    "xxx": {config}
}
```

**Comment by NeonDaniel** [comment]
I think this may be related to #161 . In general, the `get_config` methods should do minimal parsing to ensure the factory gets:
`module`, `lang`, and `module_config`; the most specific `lang` should be used, only falling back to global lang if there isn't a plugin-specific one.

The main purpose of the method here is to make sure `lang` is read from global config (if not in the plugin-specific config) and passed to plugin init

**Comment by mikejgray** [comment]
I can confirm similar issues with TTS.

mycroft.conf loaded to both /etc/mycroft/mycroft.conf and /root/.config/mycroft/mycroft.conf in a container running tts-server:
```json
{
  "lang": "de-de",
  "tts": {
    "module": "ovos_tts_plugin_espeakng",
    "ovos_tts_plugin_espeakng": {
      "lang": "de-de",
      "voice": "german-mbrola-5",
      "speed": "135",
      "amplitude": "80",
      "pitch": "20"
    }
  }
}
```

Output from logging into the container:

```bash
root@c6d9a23498f8:/# ovos-config get -k tts
Value: {'pulse_duck': False, 'module': 'ovos_tts_plugin_espeakng', 'fallback_module': '', 'ovos-tts-plugin-mimic': {'voice': 'ap'}, 
'ovos-tts-plugin-mimic3-server': {'voice': 'en_UK/apope_low'}, 'ovos_tts_plugin_espeakng': {'lang': 'de-de', 'voice': 'german-mbrola-5', 'speed': '135', 
'amplitude': '80', 'pitch': '20'}}, found in /tts
Value: {'voice': 'ap'}, found in /tts/ovos-tts-plugin-mimic
Value: {'voice': 'en_UK/apope_low'}, found in /tts/ovos-tts-plugin-mimic3-server
Value: {'lang': 'de-de', 'voice': 'german-mbrola-5', 'speed': '135', 'amplitude': '80', 'pitch': '20'}, found in /tts/ovos_tts_plugin_espeakng
```

Log of `self.config` from older version of ovos-plugin-manager that didn't swallow LOG messages:

```sh
2023-09-01 21:18:39.977 - OVOS - ovos_tts_plugin_espeakng:__init__:30 - DEBUG - {'persist_cache': False, 'lang': 'de-de'}
```

Most recent alpha does not show messages from LOG on stdout, so I can't verify the same.
