### ISSUE TITLE
No module named 'mycroft_bus_client'

### ISSUE THREAD

**Issue by NeonBohdan** [OpenVoiceOS/ovos-plugin-manager#146]
When I run `from ovos_plugin_manager.templates.tts import TTS, TTSValidator` 
It throws an error `ModuleNotFoundError: No module named 'mycroft_bus_client'`

More details [here](https://huggingface.co/spaces/neongeckocom/neon-tts-plugin-coqui)

**Comment by JarbasAl** [comment]
either install mycroft_bus_client or install latest OPM version  (from github or with --pre flag from pypi)

older versions depended on mycroft_bus_client but did not pin it in requirements.txt

**Comment by NeonDaniel** [comment]
This will be resolved and should be closed with the next stable release

**Comment by NeonDaniel** [comment]
Fixed in https://github.com/OpenVoiceOS/ovos-plugin-manager/pull/136
Stable release 0.0.23 https://github.com/OpenVoiceOS/ovos-plugin-manager/pull/165
