### ISSUE TITLE
Compatability with neon plugins

### ISSUE THREAD

**Issue by NeonBohdan** [OpenVoiceOS/OVOS-plugin-manager#57]
Ovos and Neon tts plugins has a bit different function signature
https://github.com/OpenVoiceOS/ovos-tts-server/blob/ceef8aacce4bf58b949573083c7686220f150c5e/ovos_tts_server/__init__.py#L38

[Neon speaker dict has](https://github.com/NeonGeckoCom/neon-tts-plugin-coqui/blob/2fb71105ca8350a8f6a3820ae8844f53e5cc675f/neon_tts_plugin_coqui/__init__.py#L81) `language, gender, voice` params
```
def get_tts(self, sentence: str, output_file: str, speaker: Optional[dict] = None):
    speaker: dict speaker to initialize a model for with keys:
                `language` - language code
                `gender` - optional synthesizer gender requested
                `voice` - optional synthesizer voice requested
```

Not sure how to better make them compatible

**Comment by JarbasAl** [comment]
relevant code https://github.com/OpenVoiceOS/OVOS-plugin-manager/blob/dev/ovos_plugin_manager/templates/tts.py#L685

this is happening inside the call to `execute` maybe we should make the `_synth` method public and use that in the ovos-tts-server?
